### ISSUE TITLE
Do not limit EKS Nodes to a validate set or

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-eks-gitlab#66]
explain why they must be limited.

With the current UX it is extremely fussy to figure out if your target instance type is on the very long list because:
*) CloudFormation UI does not allow typing part of the name to limit the list.
*) The list is not sorted.

This must also be maintained as AWS instances types are introduced and retired.

If it can be any normal instance type, the preference would be to remove the validation set and add a validation check that ensures some value is there.  Or, if desired, do a regex that checks all regular instance type prefixes.

**Comment by tlindsay42** [comment]
The design decision behind this is rooted in UX. The EKS nodes are not deployed until well into the deployment, so if the customer enters an incorrect instance type (typo, et cetera), it won't show up until at least 30 minutes in, and the default CloudFormation stack deployment behavior is to rollback on error, so that's at least another 30 minutes to rollback the whole stack and starting over. The trade-off in periodic maintenance overhead was deemed worthwhile by the team for providing better deployment experiences. You're absolutely right about the list needing to be alphabetically sorted though to provide a better experience. I implemented that upstream in https://github.com/aws-quickstart/quickstart-amazon-eks-nodegroup/pull/16 + https://github.com/aws-quickstart/quickstart-amazon-eks/pull/429, but hadn't cascaded it to this project yet. I just updated the list again in https://github.com/aws-quickstart/quickstart-amazon-eks-nodegroup/pull/17 and https://github.com/aws-quickstart/quickstart-amazon-eks/pull/489, so once the latter is merged in, I'll propagate it here.
