### ISSUE TITLE
Ran Twice, Failed Twice, Rollback Failed Twice

### ISSUE THREAD

**Issue by hswope-arcweb** [aws-quickstart/quickstart-eks-gitlab#93]
I'm sure this is not a very helpful issue, since I am finding it difficult to trouble shoot. But this seems to always be the way with cloud formation. But anyway I have attempted to run the quick start twice both times it has failed and then the rollback has failed.

I am attempting to create the quick start stack though the cloud formation interface. I click on the link from the gitlab doc:

https://docs.gitlab.com/ee/install/aws/gitlab_hybrid_on_aws.html

This takes me to:

https://aws-quickstart.github.io/quickstart-eks-gitlab/

I click on the link which takes me to the cloud formation interface based on:

https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-eks-gitlab/templates/gitlab-entry-new-vpc.template.yaml

The latest creation fails with an error of:
was not successfully created: The following resource(s) failed to create: [EKSStack].

Then the rollback fails with:

was not successfully deleted: The following resource(s) failed to delete: [RBACRole, JobResource, ServiceAccount].

My first attempt seemed to get further, before failing but I didn't record any info. 

I have successfully rolled my own template manually using the previous HA doc, but really wanted to give this a try prior to deploying. In theory it seems a bit more robust, but I don't want to roll my own all over again on Kubernetes. 

I know there is not much to go on here, but any thoughts appreciated. I'd still like to kick the tires on this.

**Comment by gargana** [comment]
Running this tool: https://github.com/aws-quickstart/quickstart-amazon-eks/blob/main/scripts/gather_logs.sh

`usage: ./gather-logs.sh REGION STACK_ID`

should collect all the relevant logs for the underlying Amazon EKS Quick Start deployment and CloudFormation stacks in one place.

[RBACRole, JobResource, ServiceAccount] - unless I am mistaken these are **"Kubernetes"** resources which are perhaps no longer present on the Kubernetes Cluster. Deleting the stack which contains them, while selecting "retain" for these resources, should allow you to cleanly rollback.

I suspect they were not created in the cluster due to the initial failure the stack experienced. Without knowing why the **"EKSStack"** failed it is only conjecture.

If you are able to provide some scrubbed logs once you have taken I a look I may be able to assist further. The logs collector should work even for **"DELETED"** stacks if they are recent enough.

**Comment by hswope-arcweb** [comment]
Ah. Thanks. I was thinking the gateways might be the culprit. I was trying a 3 AZ configuration. This would use up my IP's and then the bastion would have put me over the limit. I will request another 5 block which should hopefully sort me out. Thanks again for your assistance.
